### ISSUE TITLE
SA0760 module

### ISSUE THREAD

**Issue by bwired-nl** [C19HOP/WiSafe2-to-HomeAssistant-Bridge#3]
nice project, thanks
pcb stil available?
otherwise where best to order?

does it work for Sa0760 rf module which is in the wst-630-bnl? i guess it does
thanks

**Comment by C19HOP** [comment]
Hi, 
I don't have any PCBs I'm afraid. When I ordered mine, I used JLCPCB.

As long as the module is WiSafe-2, it should work. Just check it's not a zigbee/z-wave type radio. I think they briefly made such a radio available, but they were not common.
The only alarms & radios I've personally tested are the ones listed in the description / discussed in the HA forums.

I haven't been able to give any time to the project lately. But I'll aim to review issues & improvements again later this year.

Thanks.
